### ISSUE TITLE
Modules installed with 'npm install' are not available in build dir

### ISSUE THREAD

**Issue by luminosuslight** [hpicgs/node-embed#17]
The README suggest to install the required npm packages with `npm install`. This installs them in the `node_modules` folder in the current directory. The modules are then not available if the program is build and executed in different directory.

A workaround is to copy the `node_modules` folder to the directory where the binary is executed.

**Comment by justus-hildebrand** [comment]
Played around with this a bit, here's a possible explanation:
The only way I could reproduce this was when the executed **js-file** is not in the same directory as or a subdirectory of the one where ```npm install``` is called. The reason for this is how nodejs [looks up it's includes](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders).
So as long as we don't move/copy the js-files, as we discussed earlier in today's meeting, this should not be an issue.

Let me know if I got it wrong :)

**Comment by luminosuslight** [comment]
> The only way I could reproduce this was when the executed js-file is not in the same directory as or a subdirectory of the one where npm install is called.

Yes, this was the case for me. The build directory was _next to_ the node-embed directory. This is the default for Qt Creator, but I think it is the best, if we just document that we don't support this.

**Comment by sbusch42** [comment]
It shouldn't matter where the build directory is, as long as you load the scripts from their original location, i.e., a data directory, and call npm install in that directory.

**Comment by luminosuslight** [comment]
Ah, my bad, now I got it. Yes, it works if I load the js file from the source directory :+1:
