### ISSUE TITLE
Verify Mac build works

### ISSUE THREAD

**Issue by cmfcmf** [hpicgs/node-embed#5]

**Comment by luminosuslight** [comment]
Fixed libnode filename.
Still doesn't build atm.

```
[ 33%] Linking CXX executable ../../node-embed.app/Contents/MacOS/node-embed
Undefined symbols for architecture x86_64:
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__init(char const*, unsigned long)", referenced from:
      RssFeed::cppLog(v8::FunctionCallbackInfo<v8::Value> const&) in RssFeed.cpp.o
```

**Comment by luminosuslight** [comment]
The build works with a clean CMake environment. In Qt Creator one has to create a new _Kit_ for this, that doesn't modify CMake variables.

The next problem is that the dylib is not found.
A workaround is:
```
cp libnode.59.dylib /usr/local/lib/libnode.59.dylib
```

**Comment by luminosuslight** [comment]
Because the build works and only a packaging / requirements issue remains, this is considered closed.
